-- funding_intelligence — PostgreSQL / Neon
-- Os IDs importados podem ser preservados com GENERATED BY DEFAULT AS IDENTITY.

CREATE TABLE IF NOT EXISTS fontes_financiamento (
    id_fonte TEXT PRIMARY KEY,
    nome_fonte TEXT,
    sigla TEXT,
    pais TEXT,
    categoria TEXT,
    tipo_financiador TEXT,
    url_principal TEXT,
    url_oportunidades TEXT,
    metodo_coleta TEXT,
    idioma TEXT,
    periodicidade_atualizacao TEXT,
    observacoes TEXT
);

CREATE TABLE IF NOT EXISTS oportunidades (
    id_registro TEXT PRIMARY KEY,
    entidade TEXT,
    pais_origem TEXT,
    titulo TEXT,
    subtitulo TEXT,
    descricao_resumida TEXT,
    descricao_completa TEXT,
    tipo_oportunidade TEXT,
    modalidade TEXT,
    area_tematica TEXT,
    palavras_chave TEXT,
    elegibilidade TEXT,
    publico_alvo TEXT,
    nivel_academico TEXT,
    instituicao_financiadora TEXT,
    valor_financiado DOUBLE PRECISION,
    moeda TEXT,
    data_publicacao DATE,
    data_abertura DATE,
    data_limite DATE,
    data_encerramento DATE,
    status_oportunidade TEXT,
    link_origem TEXT,
    link_detalhe TEXT,
    link_documento_pdf TEXT,
    idioma TEXT,
    localidade TEXT,
    observacoes TEXT,
    texto_bruto TEXT,
    pagina_coletada INTEGER,
    fonte_oficial TEXT
        REFERENCES fontes_financiamento(id_fonte)
        ON DELETE SET NULL,
    data_hora_coleta TIMESTAMPTZ,
    hash_deduplicacao TEXT UNIQUE,
    campus TEXT,
    campos_inferidos_ia TEXT,
    enrichment_status TEXT DEFAULT 'pendente',
    enrichment_model TEXT,
    enrichment_at TIMESTAMPTZ,
    enrichment_error TEXT,
    aderencia_naval_nivel TEXT,
    aderencia_naval_justificativa TEXT,
    ideia_projeto_consorcio TEXT,
    aderencia_sertao_nivel TEXT,
    aderencia_sertao_justificativa TEXT,
    ideia_projeto_sertao TEXT,
    aderencia_aero_nivel TEXT,
    aderencia_aero_justificativa TEXT,
    ideia_projeto_aero TEXT,
    aderencia_digital_nivel TEXT,
    aderencia_digital_justificativa TEXT,
    ideia_projeto_digital TEXT,
    aderencia_park_nivel TEXT,
    aderencia_park_justificativa TEXT,
    ideia_projeto_park TEXT
);

CREATE TABLE IF NOT EXISTS migration_flags (
    flag TEXT PRIMARY KEY,
    applied_at TIMESTAMPTZ
);

CREATE TABLE IF NOT EXISTS buscas_salvas (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome_busca TEXT,
    query_text TEXT,
    payload_avancado JSONB,
    alerta_ativo BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMPTZ,
    last_run_at TIMESTAMPTZ
);

CREATE TABLE IF NOT EXISTS editais_rastreados (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_oportunidade TEXT UNIQUE
        REFERENCES oportunidades(id_registro)
        ON DELETE RESTRICT,
    status_usuario TEXT,
    observacoes TEXT,
    tracked_at TIMESTAMPTZ,
    updated_at TIMESTAMPTZ
);

CREATE TABLE IF NOT EXISTS perfil_usuario (
    id INTEGER PRIMARY KEY,
    nome_usuario TEXT,
    instituicao TEXT,
    palavras_chave_preferidas TEXT,
    areas_preferidas TEXT,
    paises_preferidos TEXT,
    financiadores_preferidos TEXT,
    tipos_oportunidade_preferidos TEXT,
    elegibilidade_preferida TEXT,
    updated_at TIMESTAMPTZ
);

CREATE TABLE IF NOT EXISTS historico_buscas (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    query_text TEXT,
    filtros_json JSONB,
    executed_at TIMESTAMPTZ
);

CREATE TABLE IF NOT EXISTS colaboradores (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome TEXT,
    instituicao TEXT,
    pais TEXT,
    area TEXT,
    palavras_chave TEXT,
    email TEXT
);

CREATE TABLE IF NOT EXISTS logs_coleta (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fonte TEXT,
    metodo_coleta TEXT,
    status_execucao TEXT,
    mensagem TEXT,
    n_paginas INTEGER,
    n_registros INTEGER,
    url TEXT,
    data_execucao TIMESTAMPTZ
);

CREATE TABLE IF NOT EXISTS pesquisadores_vencedores (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome TEXT,
    email TEXT,
    instituicao TEXT,
    expertise TEXT
);

CREATE TABLE IF NOT EXISTS projetos_aprovados (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    titulo_projeto TEXT,
    pesquisador_id INTEGER
        REFERENCES pesquisadores_vencedores(id),
    edital_titulo TEXT,
    ano INTEGER,
    palavras_chave TEXT
);

CREATE TABLE IF NOT EXISTS metrics_coleta (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fonte TEXT,
    "timestamp" TIMESTAMPTZ,
    metric_type TEXT,
    metric_value DOUBLE PRECISION,
    context JSONB
);

-- Índices auxiliares. PKs e restrições UNIQUE já criam seus próprios índices.
CREATE INDEX IF NOT EXISTS idx_oportunidades_fonte_oficial
    ON oportunidades (fonte_oficial);

CREATE INDEX IF NOT EXISTS idx_projetos_aprovados_pesquisador_id
    ON projetos_aprovados (pesquisador_id);

CREATE INDEX IF NOT EXISTS idx_logs_coleta_status_data
    ON logs_coleta (status_execucao, data_execucao);

CREATE INDEX IF NOT EXISTS idx_metrics_coleta_tipo_timestamp
    ON metrics_coleta (metric_type, "timestamp");

-- ─── Supabase Auth: Validação de Domínios de E-mail de Cadastro ────────────────
-- Execute o bloco abaixo no SQL Editor do Supabase Dashboard para restringir
-- cadastros exclusivamente para os domínios institucionais (@fieb, @fbter, @fbest, @senaicimatec):

/*
CREATE OR REPLACE FUNCTION public.check_email_domain()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY DEFINER SET search_path = public, auth
AS $$
DECLARE
  allowed_domains text[] := ARRAY['fieb.org.br', 'fbter.org.br', 'fbest.org.br', 'senaicimatec.com.br', 'cimatec.com.br'];
  user_domain text;
BEGIN
  user_domain := lower(split_part(NEW.email, '@', 2));
  IF NOT (user_domain = ANY(allowed_domains)) THEN
    RAISE EXCEPTION 'Cadastro bloqueado: Apenas e-mails institucionais (@fieb.org.br, @fbter.org.br, @fbest.org.br, @senaicimatec.com.br) são permitidos.';
  END IF;
  RETURN NEW;
END;
$$;

GRANT EXECUTE ON FUNCTION public.check_email_domain() TO anon, authenticated, service_role;

DROP TRIGGER IF EXISTS ensure_email_domain ON auth.users;
CREATE TRIGGER ensure_email_domain
BEFORE INSERT ON auth.users
FOR EACH ROW
EXECUTE FUNCTION public.check_email_domain();
*/

