db_path <- "R/helpers_db.R"
txt <- readLines(db_path, encoding = "UTF-8", warn = FALSE)

part_a <- '("pesquisa aplicada" OR "applied research" OR "investigación aplicada" OR "desenvolvimento tecnológico" OR "technological development" OR "desarrollo tecnológico" OR PD&I OR R&D OR I+D OR "manufatura avançada" OR "advanced manufacturing" OR "manufactura avanzada" OR "metrologia industrial" OR "industrial metrology" OR "metrología industrial" OR "ensaio laboratorial" OR "laboratory testing" OR "ensayo de laboratorio" OR calibração OR calibration OR calibración OR "certificação de produto" OR "product certification" OR "certificación de producto" OR prototipagem OR prototyping OR prototipado OR escalonamento OR "scale-up" OR escalamiento OR "planta piloto" OR "pilot plant" OR "planta piloto" OR "transferência de tecnologia" OR "technology transfer" OR "transferencia de tecnología" OR "propriedade intelectual" OR "intellectual property" OR "propiedad intelectual" OR patente OR patent OR patente OR "extensión tecnológica" OR "technological extension" OR "extensión tecnológica" OR "consultoria tecnológica" OR "descarbonização industrial" OR "industrial decarbonization" OR "descarbonización industrial" OR "hidrogênio verde" OR "green hydrogen" OR "hidrógeno verde" OR "economia circular" OR "circular economy" OR "economía circular" OR bioeconomia OR bioeconomy OR bioeconomía OR "biotecnologia industrial" OR "industrial biotechnology" OR "biotecnología industrial" OR petroquímica OR petrochemicals OR petroquímica OR automotivo OR automotive OR automotriz OR "dispositivos médicos" OR "medical devices" OR "dispositivos médicos" OR fármacos OR pharmaceuticals OR fármacos OR "formação profissional tecnológica" OR "mestrado profissional" OR "doutorado industrial" OR "industrial doctorate" OR "doctorado industrial" OR EMBRAPII OR FINEP OR CNPq OR FAPESB OR BNDES OR MCTI OR "subvenção econômica" OR "chamada pública" OR "public call" OR "convocatoria pública" OR "edital de inovação" OR "innovation call" OR "encomenda tecnológica" OR ETEC OR ICT OR "Lei do Bem" OR "marco legal de CT&I" OR "Rota 2030" OR "hub de inovação" OR "innovation hub" OR aceleradora OR accelerator OR aceleradora OR incubadora OR incubator OR incubadora OR "startup industrial" OR "spin-off" OR "arranjo produtivo local" OR APL OR "cooperação universidade-empresa" OR "university-industry cooperation" OR "cooperación universidad-empresa" OR "parceria público-privada" OR "public-private partnership" OR "asociación público-privada"'

part_b <- '"Alimentos e Bebidas" OR "Food and Beverages" OR "Alimentos y Bebidas" OR "Biotecnologia Industrial" OR "Industrial Biotechnology" OR "Biotecnología Industrial" OR "Automação Industrial" OR "Industrial Automation" OR "Automatización Industrial" OR "Robótica" OR "Robotics" OR "Automotiva" OR "Automotive" OR "Automotriz" OR "Calibração e Ensaios Metrológicos" OR "Calibration and Metrological Testing" OR "Calibración y Ensayos Metrológicos" OR "Certificação" OR "Certification" OR "Certificación" OR "Construção Civil" OR "Civil Construction" OR "Construcción Civil" OR "Digitalização" OR "Digitization" OR "Digitalization" OR "Digitalización" OR "Elétrica e Eletrônica" OR "Electrical and Electronics" OR "Eléctrica y Electrónica" OR "Eletrônica Embarcada" OR "Embedded Electronics" OR "Electrónica Embebida" OR "Ferramentaria" OR "Tooling" OR "Matricería" OR "Herramental" OR "Logística e Otimização de Processos" OR "Logistics and Process Optimization" OR "Logística y Optimización de Procesos" OR "Manufatura Aditiva" OR "Additive Manufacturing" OR "Manufactura Aditiva" OR "Impressão 3D" OR "3D Printing" OR "Impresión 3D" OR "Manutenção e Confiabilidade" OR "Maintenance and Reliability" OR "Mantenimiento y Confiabilidad" OR "Materiais Avançados" OR "Advanced Materials" OR "Materiales Avanzados" OR "Engenharia de Materiais" OR "Materials Engineering" OR "Meio Ambiente" OR "Environment" OR "Medio Ambiente" OR "Sustentabilidade" OR "Sustainability" OR "Sostenibilidad" OR "ESG" OR "Petróleo e Gás" OR "Oil and Gas" OR "Petróleo y Gas" OR "Oil & Gas" OR "Produtividade Industrial" OR "Industrial Productivity" OR "Productividad Industrial" OR "Projeto Industrial" OR "Industrial Design" OR "Diseño Industrial" OR "Saúde e Biotecnologia" OR "Health and Biotechnology" OR "Salud y Biotecnología" OR "Software" OR "Inteligência Artificial" OR "Artificial Intelligence" OR "Inteligencia Artificial" OR "Big Data" OR "Supercomputação" OR "Supercomputing" OR "Supercomputación" OR "Computação em Nuvem" OR "Cloud Computing" OR "Computación en la Nube" OR "Cibersegurança" OR "Cybersecurity" OR "Ciberseguridad" OR "Tecnologias Criativas" OR "Creative Technologies" OR "Tecnologías Creativas" OR "Design Digital" OR "Digital Design" OR "Diseño Digital")'

query_sede_park <- paste0(part_a, ' OR ', part_b)

# Replace line 258 and 648 (which contain "Sede e Park", "(\"deep tech\"...")
escaped_q <- gsub('"', '\\"', query_sede_park, fixed = TRUE)

for (i in seq_along(txt)) {
  if (grepl('"Sede e Park"', txt[i], fixed = TRUE) && grepl('deep tech', txt[i], fixed = TRUE)) {
    txt[i] <- sprintf('    "Sede e Park", "%s", "{}", 1L, "Sede e Park", now, now', escaped_q)
  }
}

writeLines(txt, db_path, useBytes = TRUE)
cat("Full db_helpers updated successfully\n")
